### ISSUE TITLE
idea: Stop the update before dead battery

### ISSUE THREAD

**Issue by alxbouchard** [ThingPulse/espaper-client#21]
Hi, 
It would be nice to turn the update off and keep the last content displayed when battery is very low before Wifi have not enough battery to connect. This way even if the battery is dead the last content still displayed.

Thanks!

**Comment by marcelstoer** [comment]
Indeed, good idea. However, it has to be analyzed and discussed in a slightly larger context.
- the server knows the battery level and could offer some form of notification (e.g. email to registered user)
- the device could paint a notification bar over the existing content stating that content updates were suspended due to low battery level
